import Footer from "@/components/FooterBox/Footer";
import Navbar from "@/components/NavbarBox/Navbar";
import SideBar from "@/components/SideBarBox/SideBar";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyles, Main } from "@/styles/GlobalStyles";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dramatic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body style={{ background: "#000308 " }}>
        <StyledComponentsRegistry>
          <GlobalStyles />
          <Navbar />
          <Main>
            <SideBar />
            {children}
          </Main>
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
