// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'



// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

 
'use client';

import Footer from "@/components/FooterBox/Footer";
import Navbar from "@/components/NavbarBox/Navbar";
import SideBar from "@/components/SideBarBox/SideBar";
import StyledComponentsRegistry from "@/lib/registry";
import {GlobalStyles,Main} from "@/styles/GlobalStyles";





export default function RootLayout({
   children,
 }: {
   children: React.ReactNode
 }) {
  return (
    <html>
      <body>
        <StyledComponentsRegistry>
          <GlobalStyles />
         <Navbar/>
           <Main>
            <SideBar/>
             {children}
           </Main>
        <Footer/>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}